### ISSUE TITLE
Support floats for zoom levels

### ISSUE THREAD

**Issue by timiyay** [mapbox/sphericalmercator#19]
Currently, the functions that take a `zoom` argument return `NaN` if provided with a float zoom. It only returns sensible answers for integers

I'd like to use float-based zooms upstream, in the `mapbox/geo-viewport` library's `bounds()` function (see https://github.com/mapbox/geo-viewport/issues/5). This requires `node-sphericalmercator` to support float-based zooms as well.

The use case is to allow computing the bounding box of an image requested from the Mapbox Static Image API (which also supports floats for zoom).

**Comment by mapsam** [comment]
Added in #32 and released in version 1.1.0!
