### ISSUE TITLE
Ruby port

### ISSUE THREAD

**Issue by timiyay** [mapbox/sphericalmercator#20]
Is there any community or Mapbox interest in a Ruby port of this library?

I've already ported it to a Ruby project, including the existing test suites. If anyone is into it, I can publish it as a Rubygem. Ideally, it would be maintained by Mapbox, but it wouldn't kill me to maintain it myself (if this repo is still alive).

I should state that I only understand 50% of the geometry math in this repo, which has made it difficult to bugfix.

**Comment by tmcw** [comment]
👍 Go for it! Unfortunately, we can't adopt new projects, given that there are a few hundred that I'm already responsible for.

**Comment by tmcw** [comment]
Closing, looks like a node port did not result.

**Comment by timiyay** [comment]
I've ported the code, but not yet created a repo. After reading your cautionary blog posts around open-source, I don't think I have the time to pro-actively maintain the port.

At present, the port lives in a single project. If I ever have the need to extract it, and share it amongst multiple project, then I'll open-source it. The hard yakka will be done by that point, anyway.

**Comment by tmcw** [comment]
👍 sounds good.

**Comment by nbulaj** [comment]
Anyway, is somebody needs the same functionality, but for Ruby (as me), he can use [the Ruby port](https://github.com/nbulaj/spherical_mercator) of this library. I will try to maintain it with the latest changes from this original repo.
