### ISSUE TITLE
Issues with newer leaflet version.

### ISSUE THREAD

**Issue by ChandlerBuck** [mapbox/sphericalmercator#21]
We are developing with the newer v1.0.0 version of leaflet. When I try to load the requested tile via AJAX, I get the error;  "TypeError: this._adjustTilePoint is not a function. I can get the error to go away by using an older version of leaflet, however I would like to be able to use the 1.00 version for our project we are working on. Is there an estimated time for when you will support the newer api?

Thanks.

**Comment by tmcw** [comment]
Hi Chandler,

Thanks for the report! Unfortunately this isn't much for us to go on: without code all we have is `this._adjustTilePoint`, which is a method in Leaflet, not in this library. Given that Leaflet and node-sphericalmercator have no one way of interacting - they're completely separate libraries serving only mildly related tasks - there's really no way to determine whether the bug you're hitting is in this library, or what part of the logic or code it could be related to.

If you're interested in getting this fixed, please give much more information: what is the specific point of integration, what is the full stacktrace, not just the last line of it, provide a jsfiddle or other working example, et. cetera.

**Comment by tmcw** [comment]
Closing, without more information, this is not addressable.
