### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapbox/sphericalmercator#27]
Hi there.
When I try to install I get this message suggesting to install under the @mapbox namespace:
<pre>root@core ~# node -v
v4.7.2
root@core ~# npm -v
1.4.21
root@core ~# npm install -g sphericalmercator
npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
/usr/local/bin/xyz -> /usr/local/lib/node_modules/sphericalmercator/bin/xyz.js
/usr/local/bin/to900913 -> /usr/local/lib/node_modules/sphericalmercator/bin/to900913.js
/usr/local/bin/to4326 -> /usr/local/lib/node_modules/sphericalmercator/bin/to4326.js
/usr/local/bin/bbox -> /usr/local/lib/node_modules/sphericalmercator/bin/bbox.js
sphericalmercator@1.0.5 /usr/local/lib/node_modules/sphericalmercator
root@core ~#</pre>
Uninstalling and installing again under the @mapbox namespace there is some error when listing npm packages:
<pre>root@core lib/node_modules# npm install -g @mapbox/sphericalmercator
@mapbox/sphericalmercator@1.0.5 /usr/local/lib/node_modules/@mapbox/sphericalmercator
root@core lib/node_modules# npm ls -g
/usr/local/lib
├── UNMET DEPENDENCY @mapbox@*
├── advanced-pool@0.3.2
├─┬ async@2.1.4
│ └── lodash@4.17.4
...
...
├── tileserver-gl-styles@1.1.0
└─┬ vector-tile@1.3.0
  └── point-geometry@0.0.0

npm ERR! missing: @mapbox@*, required by undefined@undefined
npm ERR! not ok code 0
root@core lib/node_modules# </pre>

Please, could somebody give me some insight?
Best regards,
Santiago Horcajo

**Comment by tmcw** [comment]
Hi Santiago,

Any chance you can update to a version of npm 2.7.0 or newer? re: npm documentation, [npm v1 doesn't support scoped modules](https://docs.npmjs.com/getting-started/scoped-packages). npm 2, 3, 4, or any version of yarn should work.

- Tom

**Comment by SantiagoHorcajo** [comment]
Thank you very much Tom, I'll try. I think it's possible for me to update npm, I hope there's no inconvinience with node version, because I need to stay in 4.x version of node for tileserver-gl ([https://github.com/klokantech/tileserver-gl](url)).
Regards,
Santiago Horcajo

**Comment by tmcw** [comment]
Any luck, Santiago?

**Comment by SantiagoHorcajo** [comment]
Not tried yet. I'm very busy to test this at the moment. I'll keep up to date.
Thanks, Tom

**Comment by mapsam** [comment]
Hey @SantiagoHorcajo any luck here?
