### ISSUE TITLE
ll to xyz to bbox off by ~ 65 degrees

### ISSUE THREAD

**Issue by Steague** [mapbox/sphericalmercator#33]
I am taking a ll [45.523109, -122.675835] with a zoom level (12) and I'm attempting to convert it to xyz.

```
let origin = [45.523109, -122.675835, 45.523109, -122.675835];
let zoomLevel = 12;
let xyz = merc.xyz(origin, zoomLevel);
console.log("Tile", xyz);
```

This gives me: 

```
Tile { minX: 2565, minY: 2847, maxX: 2565, maxY: 2847 }
```

When I attempt to convert it back to a bbox to find the bounds of the tile, the e & w coordinates come back correctly, but the n & s coordinates are off by what looks to be about 65 degrees.

```
let bbox = merc.bbox(xyz.minX, xyz.minY, zoomLevel);
console.log("BBox", bbox);
```

Returns

```
BBox [ 45.439453125,
  -57.32652122521708,
  45.52734375,
  -57.279042764977774 ]
```

Either I am doing something wrong (most likely) or something is up.

Full code example:

```
let SphericalMercator = require('sphericalmercator');

let merc = new SphericalMercator({
    size: 256
});

let origin = [45.523109, -122.675835, 45.523109, -122.675835];
console.log("Origin", origin);

let zoomLevel = 12;
let xyz = merc.xyz(origin, zoomLevel);
console.log("Tile", xyz);

let bbox = merc.bbox(xyz.minX, xyz.minY, zoomLevel);
console.log("BBox", bbox);
```

**Comment by mapsam** [comment]
Hi @Steague - apologies for the delayed response! It looks like you're flipping latitude and longitude. Sphericalmercatore requires all xy pairs to be in `[longitude, latitude]` order. So your bounding box as an example should be

```
# order of values
[ w, s, n, e ]

# your example
[-122.675835, 45.523109, -122.675835, 45.523109]
```

That'll get you the following tile info at z12 (a single point since the bounding box is a single dimension)

```
Tile { minX: 652, minY: 1464, maxX: 652, maxY: 1464 }
```

**Comment by mapsam** [comment]
Closing - feel free to re-open if flipping lng/lat does not solve your issue!
