### ISSUE TITLE
increase upper limit of SphericalMercator.prototype.px() 

### ISSUE THREAD

**Issue by shabnomnom** [mapbox/sphericalmercator#41]
I am working on allowing an acceptable bounding box across the 180th meridian with the following coordinates: 
`[179.020,69.521872,-177.0776032,70.84436016]` and noticed that there is a[ clamped back](https://github.com/mapbox/sphericalmercator/blob/39c15e4f77a1b5d1cde7c339e89a9ec3be767453/sphericalmercator.js#L56-L57) enforced on pixel upper limit that prevents the longitude to bypass 180 in `SphericalMercator.prototype.px()`.
 Can I remove this and instead add an x and y limit on the `SphericalMercator.prototype.xyz()`. Similar to the same approach that was taken #16?

**Comment by shabnomnom** [comment]
@mapsam @springmeyer I would love to hear your thoughts on this!

**Comment by mapsam** [comment]
@shabnomnom sorry for missing your request for thoughts here! Glad y'all found a path forward 🎉
